server:
  port: 8091
  servlet:
    context-path: /file
spring:
  profiles:
    active: dev,file-dev
  application:
    name: avalon-file
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: ${spring.profiles.host}:8848